### PR TITLE
Updated Deprecated dependancies and tweaked the Readme

### PR DESCRIPTION
**Pull request by therrshan**
@ameysatwe check out the readme, it is always better to have a presentable readme for people to know exactly what the repo contains. Also updated a few deprecated dependancies.

### CODE REVIEW

**Comment by ameysatwe** [comment]
That path is gonna change. Keep it relative. Dont make it specific to your repo.

**Comment by therrshan** [comment]
Assuming that youare talking about the paths in the Readme, that will not matter as long as the repos is still on my github and that link is valid. The image takes a link, and not a path.

**Comment by ameysatwe** [comment]
You gonna keep my repo????
I thought you would delete. But still a relative path is better.
Your call in the end.

**Comment by therrshan** [comment]
The link will work for now. You can change it  later to your repos link or even the path. As per your wish.

**Comment by ameysatwe** [comment]
Done. Merging

**Pull request merged**
